// ~25 common Indian car makes + a handful of popular models, used as a <datalist> for the
// free-text make/model field. It's a convenience only — the field accepts any text.
export const INDIAN_MAKES: string[] = [
  'Maruti Suzuki Swift',
  'Maruti Suzuki Baleno',
  'Maruti Suzuki Brezza',
  'Maruti Suzuki Dzire',
  'Hyundai i20',
  'Hyundai Creta',
  'Hyundai Venue',
  'Hyundai Verna',
  'Tata Nexon',
  'Tata Punch',
  'Tata Harrier',
  'Mahindra Thar',
  'Mahindra Scorpio-N',
  'Mahindra XUV700',
  'Kia Seltos',
  'Kia Sonet',
  'Toyota Innova Crysta',
  'Toyota Fortuner',
  'Honda City',
  'Honda Amaze',
  'Volkswagen Virtus',
  'Skoda Slavia',
  'Renault Kwid',
  'MG Hector',
  'Nissan Magnite',
  'BMW 3 Series',
  'Mercedes-Benz C-Class',
  'Audi Q3',
];
